### ISSUE TITLE
compilation fails with gcc6

### ISSUE THREAD

**Issue by tru7** [linknx/linknx#31] opened 2017-09-01 16:58 UTC
does not compile on a system with gcc6 like Debian Stretch mainly because of including math.h in src/suncalc.cpp. It succeeds if this is changed to include cmath, but there are many warnings which should be addressed.

**Comment by 2franix** [comment] 2017-09-07 18:32
I'll take a look at the warnings. I have to build linknx for Stretch for my own purpose anyway. Thanks for pointing this out @tru7 :)

**Comment by 2franix** [comment] 2017-09-17 21:19
I fixed all warnings with gcc6. c++11 functionality such as std::unique_ptr is now required to build linknx but I believe this is acceptable. But I am still fixing Travis' configuration to make it build with gcc6.

For now, the fix is in branch issue31. All tests pass.
I will merge it on master once I have had time to test it on my own installation. Unless @tru7 is faster to report here that it works well for him ;)

**Comment by tru7** [comment] 2017-09-18 18:19
branch issue31 compiles well for gcc v6 now. My possibilities for testing are very limited on this Debian system, at least "linknx -V" runs fine.
However branch issue31 breakt on older gcc, Here with gcc version 4.9.2 (Debian 4.9.2-10) it stops with:
In file included from ruleserver.cpp:24:0:
ioport.h:112:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<RxThread> rxThread_m;
          ^
Makefile:413: recipe for target 'ruleserver.o' failed

**Comment by 2franix** [comment] 2017-09-18 21:00
This is due to c++11. Travis had the same issue before I reconfigured it to use gcc6.
With gcc4, -std=c++0x may help. Or I can get rid of that unique_ptr feature, as it is used only once.
I'll have a look.
But at some point, we'll have to accept to break with older GCC anyway.

**Comment by tru7** [comment] 2017-09-19 05:40
@2franix agreed, but gcc 4.9.2 is an Debian Jessie which was the stable version until recently. So it's too early to drop that I think. And it also fails on current Ubuntu LTS with gcc 5.4.0. Good work anyway, thanks.

**Comment by 2franix** [comment] 2017-09-19 21:04
I fixed the problem by removing this unique_ptr usage. It was not worth the trouble.
I also changed travis' configuration to build for both gcc6 and gcc4.

**Comment by tru7** [comment] 2017-09-20 12:58
good job @2franix ! Compilation now works fine with branch issue31 for gcc with version 4, 5 and 6. Quick test with "linknx -V" also works for all versions. I guess it's time for a merge and maybe for a new release. Thanks

**Comment by 2franix** [comment] 2017-09-20 21:07
Closing the issue is premature. Until it is merged with master, it may be helpful to have it open, thus more visible, in case others encounter the same issue.
I'll merge with master once I can test this new version a little bit more.

**Closed** 2017-10-18 20:39 UTC

**Comment by 2franix** [comment] 2017-10-18 20:53
After a few days with this version in production at home, I think it is safe to consider it stable.
New release [0.0.1.34](https://github.com/linknx/linknx/releases/tag/0.0.1.34) is out, @tru7.

**Comment by neheb** [comment] 2023-01-14 21:29
@2franix out of curiosity, why is C++98 requested here?

**Comment by 2franix** [comment] 2023-01-15 10:22
Do you mean, why did I eventually refrain from using smart pointers? As stated above, we did not want to leave Debian Jessie's users behind at that time, as this version of Debian was still using gcc4. Leveraging C++11 features like `std::unique_ptr` in gcc4 is not easy, if at all possible. So I figured it was just not worth the pain and stuck to simpler C++ for now.

If this was not your question, then please elaborate.

**Comment by neheb** [comment] 2023-01-15 18:13
Current oldest supported Linux system is CentOS7 with GCC 4.8.5. It supports unique_ptr just fine.

**Comment by 2franix** [comment] 2023-01-15 20:58
According to https://gcc.gnu.org/projects/cxx-status.html, the first feature-complete version of GCC of the 2011 standard was 4.8.1. So yes, version 4.9 in Jessie was fine and my initial fix would have built with `-std=c++11`. I did not take the time to review the standard back then, as the simplest solution was just not to use `std::unique_ptr`.
